name: Submódulo - Entrega Continua (CD)

on:
  workflow_call:
    inputs:
      env_target:
        required: true
        type: string
      parent_run_id:
        required: true
        type: string

jobs:
  execute_cd:
    name: Desplegar Artefactos [CD Orquestador - ${{ github.repository_owner }} ]
    runs-on: ubuntu-latest
    # Vincula entornos protegidos de forma dinámica
    environment: ${{ inputs.env_target == 'production' && 'main' || inputs.env_target }}
    permissions:
      contents: write
    steps:
      # =======================================================================
      # PASO 1: Descargar el paquete unificado (Mismo nombre que el maestro)
      # =======================================================================
      - name: 1.Descargar Paquete de Trabajo con Binarios Certificados
        uses: actions/download-artifact@v4
        with:
          name: workspace-package # 🎯 Sincronizado con el maestro
          path: .
          run-id: ${{ inputs.parent_run_id }}
      
     
       
      # ========================================================================
      # PASO 2: Ejecución Multi-Proveedor Híbrida 100% Delegada              === 
      # ========================================================================
      - name: 2. Ejecutar Pipeline de Despliegue Híbrido (Bash CD)
        env:
          # Inyectamos el Vault completo como variable de entorno segura en RAM
          # Los scripts de Bash se encargarán de parsearlo internamente
          SECURE_VAULT: ${{ secrets.SECURE_VAULT }}
          TOKEN_REPO_ORIGINAL: ${{ steps.load_token.outputs.token_github_repo_original }}
          TOKEN_GITHUB_REPO_TMP: ${{ github.token }}
          
        run: |
          # 1. Asegurar permisos de ejecución de forma absoluta usando variables de entorno de GitHub
          chmod +x $GITHUB_WORKSPACE/src/templates-cicd/*.sh
          
          # 2. Posicionarse en el código de la aplicación
          cd $GITHUB_WORKSPACE/src/app-code
          
          # 3. Delegar la orquestación pasando el payload y el entorno meta
          $GITHUB_WORKSPACE/src/templates-cicd/run-cd.sh "${{ inputs.env_target }}"

          
          #TARGET_REPO="${{ steps.parse_payload.outputs.target_repo }}"
          #TOKEN="${{ steps.load_token.outputs.token_github_repo_original }}"
          
          #echo "[CD ORCHESTRATOR] Forzando activación de Pages para: $TARGET_REPO..."
          
          # Esperamos 3 segundos rápidos para asegurar la propagación de la rama remota
          # sleep 3
          
          # Enviamos la petición de activación
          # curl -s -X POST \
          #  -H "Authorization: token $TOKEN" \
          #  -H "Accept: application/vnd.github+json" \
          #  "https://api.github.com/repos/${TARGET_REPO}/pages" \
          #  -d '{"source":{"branch":"gh-pages","path":"/"}}' \
          #  -o /dev/null -w "%{http_code}" | grep -E "201|409" || true