name: 🧪 Submódulo - Integración Continua (CI)

on:
  workflow_call:
    inputs:
      parent_run_id:
        required: true
        type: string

jobs:
  execute_ci:
    name: Analizar y Compilar Componente
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Paquete Inmutable de Trabajo
        uses: actions/download-artifact@v4
        with:
          name: workspace-package
          path: src/
          run-id: ${{ inputs.parent_run_id }}

      - name: Ejecutar Ciclo de Integración Continua Genérico [run_ci]
        run: |
          # 1. Asegurar permisos de ejecución de forma absoluta usando variables del Runner
          chmod +x $GITHUB_WORKSPACE/src/templates-cicd/*.sh

          # 2. Posicionarse en el código de la app
          cd $GITHUB_WORKSPACE/src/app-code

          # 3. Lanzar el enrutador maestro pasando el payload
          $GITHUB_WORKSPACE/src/templates-cicd/run-ci.sh $GITHUB_WORKSPACE/src/payload.json

      - name: Actualizar Paquete Inmutable con Binarios Compilados
        uses: actions/upload-artifact@v4
        with:
          name: workspace-caja-negra
          path: src/
          overwrite: true
          retention-days: 1